import re

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.api.deps import get_current_user
from app.config import get_settings
from app.database import get_db
from app.models import Certificate, User
from app.schemas.cert import (
    CertOut,
    CsrIn,
    ImportCaIn,
    ImportServerIn,
    ImportSignedIn,
    SelfSignedIn,
    SubjectIn,
    TlsStatusOut,
)
from app.services import app_settings, certs, events

router = APIRouter(prefix="/system/certificates", tags=["certificates"])


def _to_out(row: Certificate) -> CertOut:
    return CertOut(
        id=row.id,
        name=row.name,
        kind=row.kind,
        status=row.status,
        subject=row.subject,
        issuer=row.issuer,
        san=row.san,
        serial=row.serial,
        fingerprint_sha256=row.fingerprint_sha256,
        key_type=row.key_type,
        is_self_signed=row.is_self_signed,
        not_before=row.not_before,
        not_after=row.not_after,
        has_key=bool(row.private_key_pem),
        has_csr=bool(row.csr_pem),
        has_chain=bool(row.chain_pem),
        created_at=row.created_at,
        updated_at=row.updated_at,
    )


def _subject(payload: SubjectIn) -> certs.SubjectFields:
    return certs.SubjectFields(
        common_name=payload.common_name,
        organization=payload.organization,
        organizational_unit=payload.organizational_unit,
        country=payload.country,
        state=payload.state,
        locality=payload.locality,
        email=payload.email,
    )


@router.get("", response_model=list[CertOut])
def list_certs(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    rows = db.scalars(select(Certificate).order_by(Certificate.kind, Certificate.id.desc())).all()
    return [_to_out(r) for r in rows]


@router.get("/status", response_model=TlsStatusOut)
def tls_status(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    active = certs.active_server_cert(db)
    keys = ("https_redirect", "hsts_enabled", "hsts_max_age", "tls_min_version",
            "system_hostname", "organization_name")
    values = app_settings.get_all(db)
    return TlsStatusOut(
        https_ready=active is not None,
        active_certificate=_to_out(active) if active else None,
        tls_dir=get_settings().tls_dir,
        settings={k: values.get(k, "") for k in keys},
    )


@router.get("/{cert_id}/download", response_class=PlainTextResponse)
def download(cert_id: int, part: str = "cert", db: Session = Depends(get_db),
             user: User = Depends(get_current_user)):
    row = db.get(Certificate, cert_id)
    if row is None:
        raise HTTPException(404, "Not found")
    mapping = {"cert": row.cert_pem, "csr": row.csr_pem, "chain": row.chain_pem}
    if part not in mapping:
        raise HTTPException(422, "part must be one of cert|csr|chain")
    pem = mapping[part]
    if not pem:
        raise HTTPException(404, f"No {part} available for this entry")
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", row.name).strip("_") or "certificate"
    filename = f"{safe}.{'csr' if part == 'csr' else 'pem'}"
    return PlainTextResponse(
        pem, headers={"Content-Disposition": f'attachment; filename="{filename}"'}
    )


@router.post("/self-signed", response_model=CertOut)
def self_signed(payload: SelfSignedIn, db: Session = Depends(get_db),
                user: User = Depends(get_current_user)):
    try:
        row = certs.generate_self_signed(
            db, payload.name, _subject(payload.subject), payload.sans,
            days=payload.days, key_type=payload.key_type, activate_now=payload.activate,
        )
    except certs.CertError as exc:
        raise HTTPException(422, str(exc)) from exc
    events.emit(db, "info", "system", f"Self-signed certificate created by {user.username}",
                {"name": payload.name, "activated": payload.activate})
    db.commit()
    return _to_out(row)


@router.post("/csr", response_model=CertOut)
def create_csr(payload: CsrIn, db: Session = Depends(get_db),
               user: User = Depends(get_current_user)):
    try:
        row = certs.generate_csr(db, payload.name, _subject(payload.subject),
                                 payload.sans, key_type=payload.key_type)
    except certs.CertError as exc:
        raise HTTPException(422, str(exc)) from exc
    events.emit(db, "info", "system", f"CSR generated by {user.username}", {"name": payload.name})
    db.commit()
    return _to_out(row)


@router.post("/{cert_id}/import-cert", response_model=CertOut)
def import_signed(cert_id: int, payload: ImportSignedIn, db: Session = Depends(get_db),
                  user: User = Depends(get_current_user)):
    try:
        row = certs.import_signed_cert(db, cert_id, payload.cert_pem, payload.chain_pem,
                                       activate_now=payload.activate)
    except certs.CertError as exc:
        raise HTTPException(422, str(exc)) from exc
    events.emit(db, "info", "system", f"Signed certificate imported by {user.username}",
                {"id": cert_id, "activated": payload.activate})
    db.commit()
    return _to_out(row)


@router.post("/import-server", response_model=CertOut)
def import_server(payload: ImportServerIn, db: Session = Depends(get_db),
                  user: User = Depends(get_current_user)):
    try:
        row = certs.import_server_cert(db, payload.name, payload.cert_pem, payload.key_pem,
                                       payload.chain_pem, activate_now=payload.activate)
    except certs.CertError as exc:
        raise HTTPException(422, str(exc)) from exc
    events.emit(db, "info", "system", f"Server certificate+key imported by {user.username}",
                {"name": payload.name, "activated": payload.activate})
    db.commit()
    return _to_out(row)


@router.post("/ca", response_model=CertOut)
def import_ca(payload: ImportCaIn, db: Session = Depends(get_db),
              user: User = Depends(get_current_user)):
    try:
        row = certs.import_ca(db, payload.name, payload.cert_pem)
    except certs.CertError as exc:
        raise HTTPException(422, str(exc)) from exc
    certs.materialize(db)
    events.emit(db, "info", "system", f"CA certificate imported by {user.username}",
                {"name": payload.name})
    db.commit()
    return _to_out(row)


@router.post("/{cert_id}/activate", response_model=CertOut)
def activate(cert_id: int, db: Session = Depends(get_db),
             user: User = Depends(get_current_user)):
    try:
        row = certs.activate(db, cert_id)
    except certs.CertError as exc:
        raise HTTPException(422, str(exc)) from exc
    events.emit(db, "info", "system", f"Certificate activated by {user.username}",
                {"id": cert_id, "subject": row.subject})
    db.commit()
    return _to_out(row)


@router.delete("/{cert_id}", status_code=204)
def delete(cert_id: int, db: Session = Depends(get_db),
           user: User = Depends(get_current_user)):
    try:
        certs.delete(db, cert_id)
    except certs.CertError as exc:
        raise HTTPException(422, str(exc)) from exc
    events.emit(db, "info", "system", f"Certificate deleted by {user.username}", {"id": cert_id})
    db.commit()
