"""initial

Revision ID: d5076da0b635
Revises: 
Create Date: 2026-06-12 17:53:12.563234

"""
from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('blocklist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changelog_object_id'), 'changelog', ['object_id'], unique=False)
    op.create_index(op.f('ix_changelog_object_type'), 'changelog', ['object_type'], unique=False)
    op.create_index(op.f('ix_changelog_ts'), 'changelog', ['ts'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=4096), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_ts'), 'deployments', ['ts'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_ts'), 'events', ['ts'], unique=False)
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_container', sa.Boolean(), nullable=False),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['networks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networks_cidr'), 'networks', ['cidr'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dhcp_subnets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeds_slug'), 'feeds', ['slug'], unique=True)
    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('mac', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'ip', name='uq_network_ip')
    )
    op.create_index(op.f('ix_ip_addresses_ip'), 'ip_addresses', ['ip'], unique=False)
    op.create_table('network_tags',
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('network_id', 'tag_id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('serial', sa.Integer(), nullable=False),
    sa.Column('default_ttl', sa.Integer(), nullable=False),
    sa.Column('soa_mname', sa.String(length=255), nullable=False),
    sa.Column('soa_rname', sa.String(length=255), nullable=False),
    sa.Column('refresh', sa.Integer(), nullable=False),
    sa.Column('retry', sa.Integer(), nullable=False),
    sa.Column('expire', sa.Integer(), nullable=False),
    sa.Column('minimum', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=True)
    op.create_table('dhcp_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subnet_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subnet_id'], ['dhcp_subnets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dhcp_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subnet_id', sa.Integer(), nullable=False),
    sa.Column('start_ip', sa.String(length=64), nullable=False),
    sa.Column('end_ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subnet_id'], ['dhcp_subnets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dhcp_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subnet_id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ip_address_id'], ['ip_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subnet_id'], ['dhcp_subnets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subnet_id', 'mac', name='uq_subnet_mac')
    )
    op.create_table('ip_tags',
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ip_id'], ['ip_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ip_id', 'tag_id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('ip_address_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ip_address_id'], ['ip_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'name', 'type', 'value', name='uq_record')
    )
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip_address_id', sa.Integer(), nullable=True),
    sa.Column('a_record_id', sa.Integer(), nullable=True),
    sa.Column('ptr_record_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['a_record_id'], ['records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ip_address_id'], ['ip_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ptr_record_id'], ['records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['dhcp_reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosts_name'), 'hosts', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hosts_name'), table_name='hosts')
    op.drop_table('hosts')
    op.drop_table('records')
    op.drop_table('ip_tags')
    op.drop_table('dhcp_reservations')
    op.drop_table('dhcp_ranges')
    op.drop_table('dhcp_options')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_table('zones')
    op.drop_table('network_tags')
    op.drop_index(op.f('ix_ip_addresses_ip'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index(op.f('ix_feeds_slug'), table_name='feeds')
    op.drop_table('feeds')
    op.drop_table('dhcp_subnets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_networks_cidr'), table_name='networks')
    op.drop_table('networks')
    op.drop_index(op.f('ix_events_ts'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_deployments_ts'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_changelog_ts'), table_name='changelog')
    op.drop_index(op.f('ix_changelog_object_type'), table_name='changelog')
    op.drop_index(op.f('ix_changelog_object_id'), table_name='changelog')
    op.drop_table('changelog')
    op.drop_table('blocklist_entries')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
